/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function registerPrivateKey(priKey?: string | undefined | null): void
export declare function deletePrivateKey(): void
export declare function readPrivateKey(generationHashSeed: string, tx: string): string
