/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function registerPrivateKey(priKey?: string | undefined | null): void
export declare function readPrivateKey(): void
